{% set version = "1.6.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fastdummies
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fastDummies_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fastDummies/fastDummies_{{ version }}.tar.gz
  sha256: bd3934fe19d7dff2723438bbb7b89334118143f8ce151d98477ae964ee5d81df

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-data.table
    - r-tibble
    - r-stringr
  run:
    - r-base
    - r-data.table
    - r-tibble
    - r-stringr

test:
  commands:
    - $R -e "library('fastDummies')"           # [not win]
    - "\"%R%\" -e \"library('fastDummies')\""  # [win]

about:
  home: https://github.com/jacobkap/fastDummies
  license: MIT
  summary: Creates dummy columns from columns that have categorical variables (character or factor types). You can also specify which columns to make dummies out of, or which columns to ignore. Also creates dummy rows from character, factor, and Date columns. This package provides a significant speed increase from creating
    dummy variables through model.matrix().
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - uday1889

# Package: fastDummies
# Type: Package
# Title: Fast Creation of Dummy (Binary) Columns and Rows from Categorical Variables
# Version: 1.5.0
# Authors@R: c( person("Jacob", "Kaplan", email = "jkkaplan6@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-0601-0387")),  person("Benjamin", "Schlegel", email = "kontakt@benjaminschlegl.ch", role =  "ctb"))
# Description: Creates dummy columns from columns that have categorical variables (character or factor types). You can also specify which columns to make dummies out of, or which columns to ignore. Also creates dummy rows from character, factor, and Date columns. This package provides a significant speed increase from creating dummy variables through model.matrix().
# Depends: R (>= 2.10)
# Imports: data.table, tibble
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/jacobkap/fastDummies
# BugReports: https://github.com/jacobkap/fastDummies/issues
# RoxygenNote: 6.1.1
# Suggests: testthat (>= 2.1.0), knitr, rmarkdown, covr, spelling
# VignetteBuilder: knitr
# Language: en-US
# NeedsCompilation: no
# Packaged: 2019-09-02 21:52:29 UTC; user
# Author: Jacob Kaplan [aut, cre] (<https://orcid.org/0000-0002-0601-0387>), Benjamin Schlegel [ctb]
# Maintainer: Jacob Kaplan <jkkaplan6@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-09-02 22:30:05 UTC
